---
title: "p8105_hw5_hw2849"
author: "Haotian Wu"
date: "11/15/2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

```

## Problem 1

```{r}
homicide_df = 
  read_csv("./homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>% 
  relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```

Let's focus on Baltimore, MD.

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")
  
baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"), ## number of unsolved
    n = n() ## total number of homicide
  )

baltimore_test = 
  prop.test(x = baltimore_summary %>% pull(unsolved), 
            n = baltimore_summary %>% pull(n))

baltimore_test %>% 
  broom::tidy()
```

Let's try to iterate across cities!

First off, write a function

```{r}
prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>% 
    summarize(
      unsolved = sum(resolution == "unsolved"), 
      n = n() 
    )
  
  city_test = 
    prop.test(x = city_summary %>% pull(unsolved), 
              n = city_summary %>% pull(n))
  
  return(city_test)
  
}

prop_test_function(baltimore_df)

homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()

```

Now, let's iterate across all cities

```{r}
results_df = 
  homicide_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

Try to make a plot showing estimates and confidence intervals

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  
```

```{r}
## another approach by map2

homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  ) %>% 
  mutate(
    test_results = map2(unsolved, n, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

## Problem 2

```{r}
tibble(
  files = list.files("./data")
)
```

## Problem 3
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```



